CREATE DATABASE SALES 

CREATE TABLE CUSTOMERS 
(
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(255), 
CUSTOMER_ADDRESS VARCHAR(255),
CUSTOMER_PHONENUMBER BIGINT,
CUSTOMER_GMAIL VARCHAR(255), 
) 
SELECT * FROM CUSTOMERS 
 
DROP TABLE CUSTOMERS; 

INSERT INTO
CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_ADDRESS,CUSTOMER_PHONENUMBER,CUSTOMER_GMAIL)
VALUES 
(1,'JAKIR' ,'HARI KRISHNA NAGAR' ,'9284500338' ,'ZAKIR.MIYAA@GMAIL.COM'),
(2,'HITESH' ,'HINJEWADI PUNE' ,'8605938178' ,'HITESH143@GMAIL.COM'),
(3,'IBRAHIM' ,'LOHEGAON PUNE' ,'9256845645' ,'IBRAHIM0786@GMAIL.COM'),
(4,'AKSHAY' ,'BANNER PUNE' ,'8484902725' ,'AKSHAY143@GMAIL.COM'),
(5,'ABHISHEK' ,'BALIA UP' ,'7028840449' ,'ABHISHEK456@GMAIL.COM'),
(6,'ABHIJEET' ,'BADEKAR VASTI DAREWADI' ,'8830133330' ,'ABHI7876@GMAIL.COM'),
(7,'BUNTY' ,'NARAYANDHOV VASTI' ,'9420013303', 'BUNTY786@GMAIL.COM'),
(8,'BALRAM' ,'RANIKHET UTTRAKHAND' ,'8530460432' ,'BALRAM0143@GMAIL.COM'),
(9,'MUNNA' ,'NAINITAAL HALDWAANI' ,'9175597624','MUNNA687@GMAIL.COM'),
(10,'SIDDHART' ,'BHINGAR AHMEDNAGAR' ,'9568456545' ,'SIDDHU123@GMAIL.COM'),
(11,'SHAMU' ,'KHARADI PUNE' ,'7276155481' ,'SAM0786@GMAIL.COM'),
(12,'NARSIMHA' ,'KADDPA' ,'8584868723' ,'NARSU321@GMAIL.COM'),
(13,'RAMA' ,'GOLUKWADI' ,'7040223313' ,'RAMA243@GMAIL.COM'),
(14,'GOPAL' ,'PAARGAO' ,'7972430953' ,'GOPU953@GMAIL.COM'),
(15,'NARESH' ,'MUKUNDNAGAR' ,'9975959143' ,'NARESH0143@GMAIL.COM'),
(16,'GANESH' ,'KULLAL VASTI' , '9456231574' ,'GANNU687@GMAIL.COM'),
(17,'RAYUDU' ,'BHOOT BANGLE KEE PICHE' ,'9762240789' ,'RAI852@GMAIL.COM'),
(18,'ROHAN' ,'WAKODI PHATA' ,'7499099598' ,'ROHAN147@GMAIL.COM'),
(19,'DADU' ,'MUNDHEKARWADI' ,'7756950234' ,'DADU369@GMAIL.COM'),
(20,'ASHISH' ,'DOKE VASTI JAMKHED' ,'7218986478' ,'ASHISH357@GMAIL.COM')

SELECT * FROM CUSTOMERS; 

INSERT INTO
CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_ADDRESS,CUSTOMER_PHONENUMBER,CUSTOMER_GMAIL)
VALUES 
(21,'ABRAR' ,'KOTHLA' ,'9665876652' ,'ABRAR786@GMAIL.COM'),
(22,'ALAU' ,'SAINIK NAGAR' ,'9325717443' ,'ALAU159@GMAIL.COM'),
(23,'SHEHNAAZ' ,'JABALPUR' ,'8569365241' ,'SHEH269@GMAIL.COM'),
(24,'NAGMA' ,'KARMBHUMI APARTMENT PUNE' ,'8284017146' ,'NAGMA2487@GMAIL.COM'),
(25,'RAVEENA' ,'CHANDIGARH' ,'8837828463' ,'RAVEENA254@GMAIL.COM'),
(26,'GUDIYA' ,'PANCHMARHI' ,'7224947929' ,'GUDII745@GMAIL.COM'),
(27,'SHAMA' ,'PARESHAN GALLI AHMEDNAGAR' ,'7478759623' ,'SHAMA456@GMAIL.COM'),
(28,'MCSTAN' ,'SLUM AREA MUMBAI' ,'9584756251' ,'BASTIKAHASTI05@GMAIL.COM'),
(29,'KAPIL' ,'PUNJAB' ,'8584632654' ,'KAPPU89@GMAIL.COM'),
(30,'AHIL' ,'RASULPUR BIHAR' ,'9284500338' ,'AHIL.MIYAA@GMAIL.COM')

ALTER TABLE CUSTOMERS 
ADD GENDER VARCHAR(255),
HEIGHT INT, WEIGHT INT;

ALTER TABLE CUSTOMERS 
DROP COLUMN GENDER;

DELETE FROM CUSTOMERS
WHERE GENDER = 'MALE'

UPDATE CUSTOMERS 
SET GENDER = 'MALE' , HEIGHT = 100,  WEIGHT = 100
WHERE CUSTOMER_ID = 30

SELECT MAX(WEIGHT)
FROM CUSTOMERS;

SELECT AVG(HEIGHT)
FROM CUSTOMERS;

SELECT COUNT(*)
FROM CUSTOMERS;

SELECT * FROM 
CUSTOMERS 
ORDER BY HEIGHT DESC

SELECT 
CUSTOMER_NAME,CUSTOMER_ADDRESS,HEIGHT 
FROM 
CUSTOMERS 
GROUP BY CUSTOMER_NAME , CUSTOMER_ADDRESS , HEIGHT  

SELECT COUNT(CUSTOMER_ID)  
FROM CUSTOMERS 
GROUP BY CUSTOMER_ID
HAVING COUNT (CUSTOMER_ID)>5;

 SELECT  
 TOP 6 HEIGHT , WEIGHT 
 FROM CUSTOMERS;
 
 SELECT  DISTINCT 
 CUSTOMER_NAME
 FROM CUSTOMERS; 
  
SELECT WEIGHT , CUSTOMER_NAME  
FROM CUSTOMERS 
WHERE HEIGHT BETWEEN 155 AND 166;

ALTER TABLE CUSTOMERS 
ADD AGE VARCHAR(50);

EXEC sp_rename "CUSTOMERS.CUSTOMER_AGE" , "AGE";

SELECT CUSTOMER_NAME , HEIGHT
FROM CUSTOMERS 
WHERE CUSTOMER_NAME = 'JAKIR' OR HEIGHT = 175;

SELECT CUSTOMER_PHONENUMBER 
FROM CUSTOMERS 
WHERE NOT CUSTOMER_PHONENUMBER = 9284500338;

SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_PHONENUMBER 
FROM CUSTOMERS 
WHERE CUSTOMER_ID IN (1,2,3,4,5);


SELECT CUSTOMER_ID, CUSTOMER_NAME 
FROM CUSTOMERS 
GROUP BY CUSTOMER_ID, CUSTOMER_NAME 

SELECT DISTINCT 
CUSTOMER_PHONENUMBER 
FROM CUSTOMERS 

select * 
from customers 
where customer_name like  'j%';

select * 
from customers
where customer_phonenumber 
like '%8';

select weight+40 as total_weight  
from customers;

select height-30 
from customers 
where customer_id =1; 

update customers 
set age = 28
where customer_id = 2; 

select customer_name
from customers 
where customer_name = any(

select customer_name 
from customers 
)
 

 select * 
 from customers
 where not customer_name = 'jakir' and not customer_id = 2;

 select customer_name,customer_address
 from customers 
 where height between 171 and 185; 

 select customer_gmail,height
 from customers 
 where customer_id is null;

 select top 4
 weight 
 from customers; 

 select customer_name,customer_address 
 into customer
 from customers;

 select * 
 from customer;

 drop 
 table customer; 

 select * 
 into customer1
 from customers 
 where 3=0;


 select * 
 from customer1;

 create view
 customer786 as
 select customer_id,customer_name,customer_address
 from customers;

 select * 
 from customer786;

 select customer_ID
 from customer786 

 select customer_name 
 from customer786 
 where customer_id between 25 and 30;

 select customer_address 
 from customer786 
 where customer_id in (17,18,19,20);
 

 select distinct
 customer_name 
 from customers; 




 





 


 




 




 SELECT * FROM CUSTOMERS; 


  